version: '3.9'

services:
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8093:8093
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/bdmibus
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=@S3rver13
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '@S3rver13'
      POSTGRES_DB: postgres