spring.application.name=ApiRestMiBus
server.port=8093

# Database
#spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:postgresql://64.225.12.113:5432/bdmibus
spring.datasource.username=postgres
spring.datasource.password=@S3rver13

security.jwt.private.key = 4fa5e01785987c3e532dbc280297b17e48825bd0c52a2792220ee52adadbb8a5
security.jwt.user.generator = BACKEND-CCG

